process.env.LSGIT_SCRYPT_N = '512'
const { makeApp, registerUser, loginRaw, extractSession, authed } = await import('./test/helpers.js')
const app = makeApp()
await registerUser(app)
const s = extractSession((await loginRaw(app, 'alice')).cookies)
await authed(app, 'POST', '/api/v1/projects', { session: s, payload: { name: 'P', path: 'p', visibility: 'public', description: '', website_url: '', default_branch: 'main', topics: [], initialize_with_readme: true } })
const pid = app.store.projects.byOwnerPath('alice', 'p').id
await authed(app, 'POST', `/api/v1/projects/${pid}/repository/commit`, { session: s, payload: { branch: 'f2', new_branch: true, start_branch: 'main', commit_message: 'x', changes: [{ path: 'other.txt', content: 'x' }] } })
const project = app.store.projects.byId(pid)
const repo = app.projects.storage.repository(project.disk_path)
const main = repo.resolveBranch('main')
const f2 = repo.resolveBranch('f2')
console.log('main:', main, 'f2:', f2)
console.log('mainCommit:', JSON.stringify(repo.readCommit(main)))
console.log('f2 parents:', repo.readCommit(f2).parents)
console.log('mergeBase:', app.repositories.mergeBase(repo, main, f2))
console.log('isAncestor(f2→main):', repo.isAncestor(f2, main))
